export const SET_VACANCY_ID = 'SET_VACANCY_ID';
export const ADD_VACANCY_TO_FAVORITES = 'ADD_VACANCY_TO_FAVORITES';
export const REMOVE_VACANCY_FROM_FAVORITES = 'REMOVE_VACANCY_FROM_FAVORITES';
export const ADD_FORM_DATA = 'ADD_FORM_DATA';
export const CLEAR_DATA = 'CLEAR_DATA';
export const CLOSE_DESCRIPTION = 'CLOSE_DESCRIPTION';
